-- ================================================================
-- GOBY — Migración: Seguridad + Persistencia (v2 — DRAFT)
-- Fecha: 2026-05-27
--
-- SUPERSEDED: este archivo era un borrador intermedio, nunca ejecutado
-- en producción de forma independiente. Todo el DDL está en la versión
-- canónica: 20260527_security_persistence_v3_1.sql
-- ================================================================
