-- ============================================================
-- Migration 20260617_001_audit_pepper_vault.sql
--
-- OBSOLETA — supersedida por 20260615_003_audit_system.sql (revisión ea18432+).
--
-- Vault no es accesible desde SET search_path en Supabase Cloud.
-- hmac_email_hash usa pepper estático en el cuerpo de la función.
-- No ejecutar este archivo.
-- ============================================================
